---
- hosts: jupyterhub
  become: yes
  tasks:
  - name: clone CHISim repository
    ansible.builtin.git:
      repo: https://github.com/VUZhuangweiKang/CHISim.git
      dest: /home/cc/CHISim
  - name: install grafana
    ansible.builtin.shell:
      cmd: sh CHISim/jupyterhub/ansible/chisim-deploy/grafana.sh
  - name: install influxdb
    ansible.builtin.shell:
      cmd: sh CHISim/jupyterhub/ansible/chisim-deploy/influxdb.sh
  - name: install rabbitmq
    ansible.builtin.shell:
      cmd: sh CHISim/jupyterhub/ansible/chisim-deploy/rabbitmq.sh
  - name: install mongodb
    ansible.builtin.shell:
      cmd: sh CHISim/jupyterhub/ansible/chisim-deploy/mongodb.sh
  - name: add mongodb user
    mongodb_user:
      database: admin
      user: chi-sim
      password: chi-sim
      state: present
      roles:
        - { role: "userAdminAnyDatabase", db: "admin" }
        - { role: "readWriteAnyDatabase", db: "admin" }
        - { role: "dbAdminAnyDatabase",   db: "admin" }
  - name: update mongodb config file
    blockinfile:
      dest: /etc/mongod.conf
      block: |
        security:
          authorization: enabled
  - name: restart mongodb
    ansible.builtin.shell:
      cmd: systemctl restart mongod
  - name: install CHISim python depedencies
    pip:
      requirements: /home/cc/CHISim/requirements.txt