---
- hosts: jupyterhub
  tasks:
  - name: start experiment
    async: 1000
    poll: 0
    shell: "{{ item }}"
    args:
      chdir: /home/cc/CHISim/simulator/
    with_items:
      -  python3 global_manager.py 
      -  sleep 20
      -  python3 resource_manager.py
      -  python3 frontend.py
      -  python3 backfill.py
      -  python3 workload.py
    register: experiment