---
- hosts: jupyterhub
  tasks:
  - name: Copy JupyterHub configuration.
    ansible.builtin.copy:
      src: srv/jupyterhub/
      dest: /srv/jupyterhub/
      
  - name: (read cryptography key)
    ansible.builtin.command: cat /srv/jupyterhub/crypt_key
    register: jupyterhub_crypt_key
    
  - name: Check out NativeAuthenticator for JupyterHub.
    ansible.builtin.git:
      repo: 'https://github.com/jupyterhub/nativeauthenticator.git'
      dest: /srv/jupyterhub/nativeauthenticator
      
  - name: Detect notebook images.
    ansible.builtin.find:
      paths: /srv/jupyterhub/nbimages
      patterns: "*.Dockerfile"
    register: notebook_images
      
  - name: Build Jupyter notebook image(s).
    community.docker.docker_image:
      build:
        path: /srv/jupyterhub
        dockerfile: "./nbimages/{{ item.path | basename }}"
      name: "notebook-{{ item.path | basename | regex_replace('.Dockerfile') }}"
      tag: latest
      source: build
      force_source: yes
    loop: "{{ notebook_images.files }}"
    loop_control:
      label: "{{ item.path | basename }}"
      
  # Passing the crypt key explicitly is required because Ansible
  # will not invoke this w/in a login shell that has sourced /etc/profile.d scripts
  - name: Start JupyterHub appliance.
    community.docker.docker_compose:
      project_src: /srv/jupyterhub
      state: present
      build: yes
    environment:
      JUPYTERHUB_CRYPT_KEY: "{{ jupyterhub_crypt_key.stdout }}"