---
- hosts: jupyterhub
  become: yes
  connection: local
  tasks:
  - name: Create Datasource
    community.grafana.grafana_datasource:
      name: "datasource-influxdb"
      grafana_url: "http://129.114.109.238:3000"
      grafana_user: "admin"
      grafana_password: "admin"
      ds_type: "influxdb"
      ds_url: "http://localhost:8086"
      database: "ChameleonSimulator"
      user: "chi-sim"
      password: "chi-sim"
      time_interval: ">1s"
      tls_ca_cert: "/etc/ssl/certs/ca.pem"

  - name: Import Grafana dashboard
    community.grafana.grafana_dashboard:
      grafana_url: "http://129.114.109.238:3000"
      state: present
      commit_message: Updated by ansible
      overwrite: yes
      path: /home/cc/CHISim/jupyterhub/ansible/chisim-deploy/grafana-dashboard.json