---
- hosts: jupyterhub
  tasks:
  - name: start experiment
    async: 1000
    poll: 0
    shell: "{{ item }}"
    args:
      chdir: /home/cc/CHISim/simulator/
    with_items:
      -  nohup python3 global_manager.py > global_manager.log &
      -  nohup python3 resource_manager.py > resource_manager.log &
      -  nohup python3 frontend.py > frontend.log &
      -  nohup python3 backfill.py > backfill.log &
      -  nohup python3 workload.py > workload.log &
    register: experiment

  - debug: var=experiment.stdout_lines