---
simulation:
  termination_policy: least_core  # ['random', 'least_core', 'least_resubmit', 'recent_deployed']
  request_predictor: baseline  # ['baseline', 'rolling_mean', 'rolling_median', 'lstm']
  scale_ratio: 10800
  credential:
    username: chi-sim
    password: chi-sim
  enable_osg: yes

framework:
  global_mgr:
    clean_run: yes
  rsrc_mgr:
    host: localhost
  frontend:
    request_forecaster:
      window: 168
      steps: 3
      retrain:
        enabled: yes
        length: 30000
  databus:
    rabbitmq: 127.0.0.1
  database:
    influxdb: 127.0.0.1
    mongodb: 127.0.0.1

workloads:
  machine_events:
    payload: ../datasets/machine_events/compute_haswell.csv
    timestamp_col: 0
  osg_jobs:
    payload: datasets/osg_jobs/osg_jobs.csv
    timestamp_col: 13
  chameleon_requests:
    payload: datasets/user_requests/lease_info.csv
    timestamp_col: -1
